/*
 * Blocks.java
 * RVO2 Library Java
 *
 * Copyright 2008 University of North Carolina at Chapel Hill
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please send all bug reports to <geom@cs.unc.edu>.
 *
 * The authors may be contacted via:
 *
 * Jur van den Berg, Stephen J. Guy, Jamie Snape, Ming C. Lin, Dinesh Manocha
 * Dept. of Computer Science
 * 201 S. Columbia St.
 * Frederick P. Brooks, Jr. Computer Science Bldg.
 * Chapel Hill, N.C. 27599-3175
 * United States of America
 *
 * <http://gamma.cs.unc.edu/RVO2/>
 */

//package edu.unc.cs.gamma.rvo;

import org.apache.commons.math3.geometry.euclidean.twod.Vector2D;
import org.apache.commons.math3.util.FastMath;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

// Example showing a demo with 100 agents split in four groups initially
// positioned in four corners of the environment. Each agent attempts to move to
// other side of the environment through a narrow passage generated by four
// obstacles. There is no road map to guide the agents around the obstacles.
class Blocks {
    // Store the goals of the agents.
    private final List<Vector2D> goals = new ArrayList<Vector2D>();

    // Random number generator.
    private final Random random = new Random();

    private void setupScenario() {
        // Specify the global time step of the simulation.
        //instance.setTimeStep(34.55);
        instance.setTimeStep(34.55);

        // Specify the default parameters for agents that are subsequently
        // added.
        instance.setAgentDefaults(185.0, 20, 15.0, 15.0, 30.0, 52.0, Vector2D.ZERO);

        // Add agents, specifying their start position, and store their goals on
        // the opposite side of the environment.
        /*
        for (int i = 0; i < 100; i=i+2) {
            for (int j = 0; j < 24; j=j+2) {
              
              if (img[j*100+i] == 1) {
                instance.addAgent(new Vector2D(random(800), random(800)));
                goals.add(new Vector2D(i*10, 200+j*10));

              }
              
            }
        }
        */
        
        for (int i = 0; i < robotNR; i++) {
            //instance.addAgent(new Vector2D(x[i], y[i]));
            //goals.add(new Vector2D(puncte[stage][i][0], puncte[stage][i][1]));
            instance.addAgent(new Vector2D(robot[i].x, robot[i].y));
            goals.add(new Vector2D(robot[i].goalX, robot[i].goalY));          

        }
        
        /*
        
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 2; j++) {
                instance.addAgent(new Vector2D(55.0 + i * 10.0, 55.0 + j * 10.0));
                goals.add(new Vector2D(-75.0, -75.0));

                instance.addAgent(new Vector2D(-55.0 - i * 10.0, 55.0 + j * 10.0));
                goals.add(new Vector2D(75.0, -75.0));

                instance.addAgent(new Vector2D(55.0 + i * 10.0, -55.0 - j * 10.0));
                goals.add(new Vector2D(-75.0, 75.0));

                instance.addAgent(new Vector2D(-55.0 - i * 10.0, -55.0 - j * 10.0));
                goals.add(new Vector2D(75.0, 75.0));
            }
        }
        
        */

        // Add (polygonal) obstacles, specifying their vertices in
        // counterclockwise order.
        /*
        final List<Vector2D> obstacle1 = new ArrayList<Vector2D>();
        obstacle1.add(new Vector2D(-10.0, 40.0));
        obstacle1.add(new Vector2D(-40.0, 40.0));
        obstacle1.add(new Vector2D(-40.0, 10.0));
        obstacle1.add(new Vector2D(-10.0, 10.0));
        instance.addObstacle(obstacle1);

        final List<Vector2D> obstacle2 = new ArrayList<Vector2D>();
        obstacle2.add(new Vector2D(10.0, 40.0));
        obstacle2.add(new Vector2D(10.0, 10.0));
        obstacle2.add(new Vector2D(40.0, 10.0));
        obstacle2.add(new Vector2D(40.0, 40.0));
        instance.addObstacle(obstacle2);

        final List<Vector2D> obstacle3 = new ArrayList<Vector2D>();
        obstacle3.add(new Vector2D(10.0, -40.0));
        obstacle3.add(new Vector2D(40.0, -40.0));
        obstacle3.add(new Vector2D(40.0, -10.0));
        obstacle3.add(new Vector2D(10.0, -10.0));
        instance.addObstacle(obstacle3);
*/

     
     //To add a "negative" obstacle,
     //* e.g., a bounding polygon around the environment, the vertices should be
     //* listed in clockwise order.

        final List<Vector2D> obstacle4 = new ArrayList<Vector2D>();
        obstacle4.add(new Vector2D(-10.0, -40.0));
        obstacle4.add(new Vector2D(-10.0, -10.0));
        obstacle4.add(new Vector2D(-40.0, -10.0));
        obstacle4.add(new Vector2D(-40.0, -40.0));
        instance.addObstacle(obstacle4);

        instance.processObstacles();
    }

    private void updateVisualization() {
        // Output the current global time.
        //System.out.print(Simulator.instance.getGlobalTime());

        // Output the current position of all the agents.
        for (int agentNo = 0; agentNo < instance.getNumAgents(); agentNo++) {
           // System.out.print(" " + instance.getAgentPosition(agentNo));
           /*
            fill(0);
            beginShape();
            vertex(-10.0*4+400, 40.0*4+400);
            vertex(-40*4+400,40*4+400);
            vertex(-40*4+400,10*4+400);
            vertex(-10*4+400,10*4+400);
            // etc;
            endShape();
            */
            //ellipse((float)instance.getAgentPosition(agentNo).getX(), (float)instance.getAgentPosition(agentNo).getY(),4.0,4.0);
            
        }

        //System.out.println();
    }

private void updateGoal(int agentNr, float x, float y) {
  goals.set(agentNr, new Vector2D(x, y));
}


    private void setPreferredVelocities() {
        // Set the preferred velocity to be a vector of unit magnitude (speed)
        // in the direction of the goal.
        for (int agentNo = 0; agentNo < instance.getNumAgents(); agentNo++) {
            Vector2D goalVector = goals.get(agentNo).subtract(instance.getAgentPosition(agentNo));
            final double lengthSq = goalVector.getNormSq();
            if (lengthSq > 1.0) {
                goalVector = goalVector.scalarMultiply(1.0 / FastMath.sqrt(lengthSq));
            }

            instance.setAgentPreferredVelocity(agentNo, goalVector);

            // Perturb a little to avoid deadlocks due to perfect symmetry.
            //final double angle = random.nextDouble() * 2.0 * FastMath.PI;
            //final double distance = random.nextDouble() * 0.0001;
            final double angle = 0;
            final double distance = 0;


            instance.setAgentPreferredVelocity(agentNo, instance.getAgentPreferredVelocity(agentNo).add(new Vector2D(FastMath.cos(angle), FastMath.sin(angle)).scalarMultiply(distance)));
        }
    }

    private boolean reachedGoal() {
        // Check if all agents have reached their goals.
        for (int agentNo = 0; agentNo < instance.getNumAgents(); agentNo++) {
            if (instance.getAgentPosition(agentNo).distanceSq(goals.get(agentNo)) > 10.0) {
                return false;
            }
        }

        return true;
    }
/*
    public static void main(String[] args) {
        final Blocks blocks = new Blocks();

        // Set up the scenario.
        blocks.setupScenario();

        // Perform (and manipulate) the simulation.
        do {
            blocks.updateVisualization();
            blocks.setPreferredVelocities();
            Simulator.instance.doStep();
        }
        while (!blocks.reachedGoal());
    }
    
  */
}
